name: jajvm_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  args: ^2.3.1
  date_format: ^2.0.6
  equatable: ^2.0.3
  io: ^1.0.3
  meta: ">=1.7.0 <1.8.0"
  path: ">=1.8.0 <2.0.0"
  process_run: ^0.12.3+2
  riverpod: ^2.0.0-dev.9
  uuid: ^3.0.6
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: any

platforms:
  windows:
